
#ifndef XK_CLASSES_H
#define XK_CLASSES_H

                                                                                       


namespace Xk
{

namespace Classes
{

enum classes
{
  XK_CLASSES_BEGIN = 457,
  _void,
  _bool,
  _char,
  _short,
  _int,
  _float,
  _double,
  _long,
  _unsigned_char,
  _unsigned_short,
  _unsigned_int,
  _unsigned_long,
  _AccumulativeSceneTimer,
  _Actor,
  _ActorMachinePart,
  _Archive,
  _Array,
  _ArrayReferenceCounter,
  _ArrayUnknown,
  _AuxiliaryScene,
  _Box,
  _BoxDescription,
  _Buffer,
  _BufferReferenceCounter,
  _BufferUnknown,
  _Callback,
  _Capsule,
  _CapsuleDescription,
  _CCDSkeletonMeshData,
  _Cloth,
  _ClothDescription,
  _ClothRaycastHit,
  _Compartment,
  _CompartmentDescription,
  _ContactPair,
  _Convex,
  _ConvexDescription,
  _D6Joint,
  _D6JointDescription,
  _DebugRenderable,
  _ErrorListener,
  _ErrorStream,
  _Exception,
  _FileArchive,
  _FileResource,
  _FileResourceProtocol,
  _FixedJoint,
  _FixedSceneTimer,
  _Fluid,
  _FluidDescription,
  _FluidDrain,
  _FluidDrainDescription,
  _FluidEmitter,
  _FluidEmitterDescription,
  _FluidPacket,
  _Geometry,
  _HeightField,
  _HeightFieldData,
  _HeightFieldGeometry,
  _HeightFieldGeometryDescription,
  _HeightFieldManager,
  _HeightFieldSample,
  _int2,
  _int3,
  _int4,
  _Joint,
  _JointDescription,
  _JointLimitDescription,
  _JointLimitSoftDescription,
  _KinematicActor,
  _KinematicController,
  _Machine,
  _MachinePart,
  _ManualHeightField,
  _ManualHeightFieldReferenceCounter,
  _ManualMesh,
  _ManualMeshReferenceCounter,
  _Material,
  _MaterialDescription,
  _Memory,
  _MemoryArchive,
  _MemoryResource,
  _MemoryResourceProtocol,
  _Mesh,
  _MeshData,
  _MeshManager,
  _MeshSerialiser,
  _MeshStats,
  _MotorDescription,
  _Notice,
  _Particle,
  _ParticleData,
  _Path,
  _PhysXCallback,
  _PhysXMeshData,
  _PhysXOutputStream,
  _PhysXParticleData,
  _PhysXPointer,
  _PhysXShapePointer,
  _PhysXUserAllocator,
  _PlaneGeometry,
  _PlaneGeometryDescription,
  _PointParticleRenderer,
  _PointRenderable,
  _PrincipalScene,
  _Ray,
  _RaycastHit,
  _RemoteDebugger,
  _RemoteDebuggerListener,
  _Renderable,
  _Resource,
  _ResourceProtocol,
  _ResourceSystem,
  _RevoluteJoint,
  _RevoluteJointDescription,
  _RigidBody,
  _RigidBodyDescription,
  _Scene,
  _SceneDescription,
  _SceneGeometry,
  _SceneLink,
  _ScenePrototype,
  _SceneRenderer,
  _SceneTimer,
  _Shape,
  _ShapeDescription,
  _SharedArray,
  _SharedBuffer,
  _SimpleBox,
  _SimpleCapsule,
  _SimplePlane,
  _SimplePointCloud,
  _SimpleSegment,
  _SimpleShape,
  _SimpleSphere,
  _SimpleTriangleMesh,
  _Singleton,
  _SoftBody,
  _SoftBodyDescription,
  _SoftBodyMesh,
  _Sphere,
  _SphereDescription,
  _SphericalJoint,
  _SphericalJointDescription,
  _SpringDescription,
  _SweepCache,
  _SweepQueryHit,
  _TBuffer,
  _TimeController,
  _TimeListener,
  _Timer,
  _TimerStep,
  _TireFunction,
  _TriangleGeometry,
  _TriangleGeometryDescription,
  _VisualDebugger,
  _VisualDebuggerMeshData,
  _Volume,
  _Warning,
  _Wheel,
  _WheelDescription,
  _WheelMachinePart,
  _World,
  _WorldDescription,
  _WorldPrototype,
  _CharacterController,
  RENDERSYSTEMS_CLASSES_BEGIN,
  USER_CLASS = 50000
};

                                                                                       

/** \brief Turns a Xk::Classes::Enum into a String and any PhysX MemoryType enum value as well.
*/
const char*  TypeToCStr(int i);

                                                                                       
} // namespace Classes
} // namespace Xk

                                                                                       
#endif
